Repository final-project-insider/BACK-LOGIN, pull requests merged in 2024-05, with the labels that each got.

#140 Feat#7 전자결재회수
  final/http/approval/approval.http
  final/src/main/java/com/insider/login/approval/builder/ApprovalBuilder.java
  final/src/main/java/com/insider/login/approval/builder/ApproverBuilder.java
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/dto/ApprovalDTO.java
  final/src/main/java/com/insider/login/approval/dto/ApproverDTO.java
  final/src/main/java/com/insider/login/approval/dto/DepartmentDTO.java
  final/src/main/java/com/insider/login/approval/dto/MemberDTO.java
  final/src/main/java/com/insider/login/approval/dto/ReferencerDTO.java
  final/src/main/java/com/insider/login/approval/dto/ResponseDTO.java
  final/src/main/java/com/insider/login/approval/entity/Approval.java
  final/src/main/java/com/insider/login/approval/entity/Department.java
  final/src/main/java/com/insider/login/approval/entity/Member.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
  final/src/main/java/com/insider/login/approval/repository/AttachmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/DepartmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/FormRepository.java
  final/src/main/java/com/insider/login/approval/repository/MemberRepository.java
  final/src/main/java/com/insider/login/approval/repository/ReferencerRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Labels: 💻Feature, 🥝Refactor

#141 feat #18 출퇴근 관련 엔티티 위치 변경
  .idea/dataSources.xml
  final/http/Leave/Leave.http
  final/http/calendar/calendar.http
  final/http/commute/commute.http
  final/http/other/notice.http
  final/http/other/user.http
  final/src/main/java/com/insider/login/approval/repository/ApprovalDepartmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalMemberRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/main/java/com/insider/login/commute/controller/CommuteController.java
  final/src/main/java/com/insider/login/commute/dto/CommuteDTO.java
  final/src/main/java/com/insider/login/commute/dto/CommuteDepartmentDTO.java
  final/src/main/java/com/insider/login/commute/dto/CommuteMemberDTO.java
  final/src/main/java/com/insider/login/commute/dto/CorrectionDTO.java
  final/src/main/java/com/insider/login/commute/dto/UpdateProcessForCorrectionDTO.java
  final/src/main/java/com/insider/login/commute/dto/UpdateTimeOfCommuteDTO.java
  final/src/main/java/com/insider/login/commute/entity/Commute.java
  final/src/main/java/com/insider/login/commute/entity/CommuteDepartment.java
  final/src/main/java/com/insider/login/commute/entity/CommuteMember.java
  final/src/main/java/com/insider/login/commute/entity/Correction.java
  final/src/main/java/com/insider/login/commute/repository/CommuteDepartmentRepository.java
  final/src/main/java/com/insider/login/commute/repository/CommuteMemberRepository.java
  final/src/main/java/com/insider/login/commute/repository/CommuteRepository.java
  final/src/main/java/com/insider/login/commute/repository/CorrectionRepository.java
  final/src/main/java/com/insider/login/commute/service/CommuteMemberService.java
  final/src/main/java/com/insider/login/commute/service/CommuteService.java
  final/src/main/java/com/insider/login/department/repository/DepartmentRepository.java
  final/src/main/java/com/insider/login/member/repository/MemberRepository.java
  final/src/main/java/com/insider/login/member/service/MemberService.java
  final/src/main/java/com/insider/login/other/notice/controller/NoticeController.java
  final/src/main/java/com/insider/login/other/notice/dto/NoticeDTO.java
  final/src/main/java/com/insider/login/other/notice/entity/Notice.java
  final/src/main/java/com/insider/login/other/notice/repository/NoticeRepository.java
  final/src/main/java/com/insider/login/other/notice/service/NoticeService.java
  final/src/test/java/com/insider/login/commute/controller/CommuteControllerTests.java
  final/src/test/java/com/insider/login/commute/service/CommuteServiceTests.java
  final/src/test/java/com/insider/login/commute/service/CommuteTests.java
  final/src/test/java/com/insider/login/other/notice/controller/NoticeControllerTests.java
  final/src/test/java/com/insider/login/other/notice/service/NoticeServiceTests.java
Labels: 🌀BugFix

#152 수정 완료
  .idea/inspectionProfiles/Project_Default.xml
  final/build.gradle
  final/http/other/department.http
  final/http/other/position.http
  final/http/other/user.http
  final/src/main/java/com/insider/login/auth/DetailsMember.java
  final/src/main/java/com/insider/login/auth/handler/CustomAuthSuccessHandler.java
  final/src/main/java/com/insider/login/auth/image/controller/ImageController.java
  final/src/main/java/com/insider/login/auth/image/dto/ImageDTO.java
  final/src/main/java/com/insider/login/auth/image/repository/ImageRepository.java
  final/src/main/java/com/insider/login/auth/image/service/ImageService.java
  final/src/main/java/com/insider/login/auth/model/service/DetailsService.java
  final/src/main/java/com/insider/login/common/utils/ConvertUtil.java
  final/src/main/java/com/insider/login/common/utils/MemberRole.java
  final/src/main/java/com/insider/login/common/utils/TokenUtils.java
  final/src/main/java/com/insider/login/department/controller/DepartmentController.java
  final/src/main/java/com/insider/login/department/dto/DepartmentDTO.java
  final/src/main/java/com/insider/login/department/entity/Department.java
  final/src/main/java/com/insider/login/department/service/DepartmentService.java
  final/src/main/java/com/insider/login/member/controller/MemberController.java
  final/src/main/java/com/insider/login/member/controller/TestController.java
  final/src/main/java/com/insider/login/member/dto/MemberDTO.java
  final/src/main/java/com/insider/login/member/dto/UpdatePasswordRequestDTO.java
  final/src/main/java/com/insider/login/member/repository/MemberRepository.java
  final/src/main/java/com/insider/login/position/controller/PositionController.java
  final/src/main/java/com/insider/login/position/dto/PositionDTO.java
  final/src/main/java/com/insider/login/position/entity/Position.java
  final/src/main/java/com/insider/login/position/repository/PositionRepository.java
  final/src/main/java/com/insider/login/position/service/PositionService.java
  final/src/main/java/com/insider/login/transferredHistory/controller/TransferredHistoryController.java
  final/src/main/java/com/insider/login/transferredHistory/dto/TransferredHistoryDTO.java
  final/src/main/java/com/insider/login/transferredHistory/entity/TransferredHistory.java
  final/src/main/java/com/insider/login/transferredHistory/repository/TransferredHistoryRepository.java
  final/src/main/java/com/insider/login/transferredHistory/service/TransferredHistoryService.java
Labels: 🌀BugFix

#155 feat #1 - [웹소켓 연결]
  final/http/other/announce.http
  final/http/other/chat.http
  final/http/other/note.http
  final/http/other/user.http
  final/src/main/java/com/insider/login/config/YmlConfig.java
  final/src/main/java/com/insider/login/member/entity/Member.java
  final/src/main/java/com/insider/login/member/repository/MemberRepository.java
  final/src/main/java/com/insider/login/member/service/MemberService.java
  final/src/main/java/com/insider/login/other/announce/controller/AnnounceController.java
  final/src/main/java/com/insider/login/other/announce/dto/AnnounceDTO.java
  final/src/main/java/com/insider/login/other/announce/entity/AncFile.java
  final/src/main/java/com/insider/login/other/announce/entity/Announce.java
  final/src/main/java/com/insider/login/other/announce/repository/AnnounceFileRepository.java
  final/src/main/java/com/insider/login/other/announce/repository/AnnounceRepository.java
  final/src/main/java/com/insider/login/other/announce/service/AnnounceService.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/Result.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/config/WebSocketBrokerConfig.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/config/WebSocketConfig.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/config/WebSocketConfigMapping.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/controller/BrokerController.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/controller/ChatRoomController.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/EntRoomDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/EntRoomReqDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/EntRoomResponseDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/EnteredRoomDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/MessageDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/RoomJoinedReqDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/RoomResponseDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/entity/EnteredRoom.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/entity/RoomStatus.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/handler/SocketHandler.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/interceptor/CustomHandshakeInterceptor.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/interceptor/WebsocketBrokerInterceptor.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/repository/EnteredRoomRepository.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/service/EnteredRoomService.java
  final/src/main/resources/application.yml
Labels: 🎈API, 💻Feature

#150 Fix#2전자결재조회테스트수정
  final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
  final/src/main/java/com/insider/login/approval/repository/ReferencerRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Labels: 🌀BugFix

#158 feat #19 - [출퇴근] 토큰 오류 수정
  final/http/commute/commute.http
  final/src/test/java/com/insider/login/commute/controller/CommuteControllerTests.java
Labels: 🌀BugFix

#167 feat #5 - [휴가, 일정, 수요조사] 휴가, 일정, 수요조사 관련
  final/src/main/java/com/insider/login/leave/entity/LeaveMember.java
  final/src/main/java/com/insider/login/leave/repository/LeaveMemberRepository.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 🌀BugFix, 💻Feature, 🔎Test, 🥝Refactor

#173 Fix#4전자결재 목록조회테스트수정
  final/http/approval/approval.http
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/dto/MemberDTO.java
  final/src/main/java/com/insider/login/approval/dto/PositionDTO.java
  final/src/main/java/com/insider/login/approval/entity/Position.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalDepartmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalMemberRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
  final/src/main/java/com/insider/login/approval/repository/AttachmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/ReferencerRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/test/java/com/insider/login/approval/controller/ApprovalControllerTest.java
  final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Labels: 💻Feature, 🔎Test, 🥝Refactor

#161 fix#3 전자결재 회수 수정
  final/http/approval/approval.http
  final/http/other/user.http
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
Labels: 🥝Refactor

#180 Refactor #2 - UTF 관련 설정 : 시큐리티 필터 + YML 설정
  final/http/approval/approval.http
  final/http/other/announce.http
  final/http/other/chat.http
  final/http/other/note.http
  final/http/other/user.http
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/dto/MemberDTO.java
  final/src/main/java/com/insider/login/approval/dto/PositionDTO.java
  final/src/main/java/com/insider/login/approval/entity/Position.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalDepartmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalMemberRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
  final/src/main/java/com/insider/login/approval/repository/AttachmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/ReferencerRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/main/java/com/insider/login/auth/DetailsMember.java
  final/src/main/java/com/insider/login/auth/config/WebConfig.java
  final/src/main/java/com/insider/login/auth/config/WebSecurityConfig.java
  final/src/main/java/com/insider/login/auth/filter/CustomAuthenticationFilter.java
  final/src/main/java/com/insider/login/auth/filter/JwtAuthorizationFilter.java
  final/src/main/java/com/insider/login/auth/handler/CustomAuthFailureHandler.java
  final/src/main/java/com/insider/login/auth/handler/CustomAuthSuccessHandler.java
  final/src/main/java/com/insider/login/auth/handler/CustomAuthenticationProvider.java
  final/src/main/java/com/insider/login/auth/model/dto/LoginDTO.java
  final/src/main/java/com/insider/login/auth/model/service/DetailsService.java
  final/src/main/java/com/insider/login/common/CommonController.java
  final/src/main/java/com/insider/login/common/utils/ConvertUtil.java
  final/src/main/java/com/insider/login/common/utils/TokenUtils.java
  final/src/main/java/com/insider/login/leave/entity/LeaveMember.java
  final/src/main/java/com/insider/login/leave/repository/LeaveMemberRepository.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
  final/src/main/java/com/insider/login/member/dto/UpdatePasswordRequestDTO.java
  final/src/main/java/com/insider/login/other/announce/controller/AnnounceController.java
  final/src/main/java/com/insider/login/other/announce/service/AnnounceService.java
  final/src/main/resources/application.yml
  final/src/test/java/com/insider/login/approval/controller/ApprovalControllerTest.java
  final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Labels: 🌀BugFix, 🥝Refactor

#181 Fix#4 전자결재 전체 코드 복구
  final/http/approval/approval.http
  final/src/main/java/com/insider/login/approval/builder/ApproverBuilder.java
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/dto/MemberDTO.java
  final/src/main/java/com/insider/login/approval/dto/PositionDTO.java
  final/src/main/java/com/insider/login/approval/entity/Position.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalDepartmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalMemberRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
  final/src/main/java/com/insider/login/approval/repository/AttachmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/ReferencerRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/test/java/com/insider/login/approval/controller/ApprovalControllerTest.java
  final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Labels: 🥝Refactor

#186 fix #2 - [로그인] 로그인할 시 아이디 int 값을 초과할 시 error 해결
  final/src/main/java/com/insider/login/auth/filter/CustomAuthenticationFilter.java
  final/src/main/java/com/insider/login/auth/filter/HeaderFilter.java
  final/src/main/java/com/insider/login/auth/handler/CustomAuthenticationProvider.java
  final/src/main/java/com/insider/login/common/utils/TokenUtils.java
Labels: 🌀BugFix

#177 fix #12 - [수요조사] 수요조사 등록 에러 해결
  final/http/other/survey.http
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
  final/src/main/java/com/insider/login/other/survey/controller/SurveyController.java
  final/src/main/java/com/insider/login/other/survey/dto/SurveyInsertRequestDTO.java
Labels: 🌀BugFix

#188 feat#14전자결재 controller 목록조회테스트
  final/http/approval/approval.http
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/test/java/com/insider/login/approval/controller/ApprovalControllerTest.java
  final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Labels: 💻Feature, 🔎Test, 🥝Refactor

#190 Dh 05 09 003fix #34 - [휴가] 사라졌던 코드 복구
  final/http/Leave/Leave.http
  final/src/main/java/com/insider/login/leave/entity/LeaveMember.java
  final/src/main/java/com/insider/login/leave/repository/LeaveMemberRepository.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 🌀BugFix

#191 Feat#15 전자결재controller등록테스트
  final/http/approval/approval.http
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/main/java/com/insider/login/auth/filter/JwtAuthorizationFilter.java
  final/src/test/java/com/insider/login/approval/controller/ApprovalControllerTest.java
  final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Labels: 💻Feature, 🔎Test, 🥝Refactor

#195 feat #12 - [캘린더] 일정 상세 컬럼 추가, 일정 코드 일부 리팩토링
  final/http/calendar/calendar.http
  final/src/main/java/com/insider/login/calendar/controller/CalendarContorller.java
  final/src/main/java/com/insider/login/calendar/dto/CalendarDTO.java
  final/src/main/java/com/insider/login/calendar/entity/Calendar.java
  final/src/main/java/com/insider/login/calendar/service/CalendarService.java
  final/src/test/java/com/insider/login/calendar/controller/CalendarControllerTests.java
Labels: 💻Feature, 🥝Refactor

#199 fix #13 - [캘린더] 실행 확인용 주석 삭제
  final/http/calendar/calendar.http
  final/src/main/java/com/insider/login/calendar/controller/CalendarContorller.java
  final/src/main/java/com/insider/login/calendar/service/CalendarService.java
Labels: 🥝Refactor

#204 fix #1 - [쪽지] 쪽지 삭제 기능을 진행하며, 엔티티 수정 추가 및 로직 변경
  final/http/other/announce.http
  final/http/other/note.http
  final/http/other/user.http
  final/src/main/java/com/insider/login/other/announce/controller/AnnounceController.java
  final/src/main/java/com/insider/login/other/announce/entity/Announce.java
  final/src/main/java/com/insider/login/other/announce/service/AnnounceService.java
  final/src/main/java/com/insider/login/other/note/controller/NoteController.java
  final/src/main/java/com/insider/login/other/note/dto/NoteDTO.java
  final/src/main/java/com/insider/login/other/note/entity/Note.java
  final/src/main/java/com/insider/login/other/note/repository/NoteRepository.java
  final/src/main/java/com/insider/login/other/note/service/NoteService.java
  final/src/test/java/com/insider/login/other/announce/service/AnnounceServiceTests.java
  final/src/test/java/com/insider/login/other/note/service/NoteServiceTests.java
Labels: 🌀BugFix, 🥝Refactor

#210 fix #2 - [쪽지] 쪽지 전체조회 정렬 상태 변경
  final/http/other/note.http
  final/src/main/java/com/insider/login/common/CommonController.java
  final/src/main/java/com/insider/login/other/note/controller/NoteController.java
Labels: 🌀BugFix, 🥝Refactor

#212 구성원 등록 기능 구현
  final/http/other/department.http
  final/http/other/position.http
  final/http/other/user.http
  final/src/main/java/com/insider/login/department/controller/DepartmentController.java
  final/src/main/java/com/insider/login/department/service/DepartmentService.java
  final/src/main/java/com/insider/login/member/controller/MemberController.java
  final/src/main/java/com/insider/login/member/dto/MemberDTO.java
  final/src/main/java/com/insider/login/member/entity/Member.java
  final/src/main/java/com/insider/login/member/service/MemberService.java
  final/src/main/java/com/insider/login/position/entity/Position.java
Labels: 🌀BugFix

#215 fix #20 - [출퇴근] testController 테스트 시 토큰 오류 이슈/ 가장 마지막 출퇴근 번호 찾기 로직 추가
  final/http/commute/commute.http
  final/src/main/java/com/insider/login/common/utils/TokenUtils.java
  final/src/main/java/com/insider/login/commute/controller/CommuteController.java
  final/src/main/java/com/insider/login/commute/dto/CommuteMemberDTO.java
  final/src/main/java/com/insider/login/commute/entity/Commute.java
  final/src/main/java/com/insider/login/commute/repository/CommuteMemberRepository.java
  final/src/main/java/com/insider/login/commute/service/CommuteService.java
  final/src/main/java/com/insider/login/member/dto/MemberDTO.java
  final/src/test/java/com/insider/login/commute/controller/CommuteControllerTests.java
  final/src/test/java/com/insider/login/commute/service/CommuteServiceTests.java
  final/src/test/java/com/insider/login/other/note/controller/NoteControllerTests.java
Labels: 🌀BugFix, 💻Feature, 🔎Test, 🥝Refactor

#218 fix #35 - [휴가] 휴가 차감 일수 계산식 수정
  final/src/main/java/com/insider/login/leave/controller/LeaveController.java
  final/src/main/java/com/insider/login/leave/entity/LeaveSubmit.java
  final/src/main/java/com/insider/login/leave/util/LeaveUtil.java
Labels: 🌀BugFix

#219 fix#5 전자결재 목록조회 page 수정
  final/http/approval/approval.http
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/main/java/com/insider/login/auth/filter/JwtAuthorizationFilter.java
Labels: 🥝Refactor

#224 feat #36 - [휴가] 서비스 클래스 리팩토링
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 🥝Refactor

#225 fix#6 전자결재 목록조회 임시저장 수정
  final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
Labels: 🌀BugFix

#227 feat #37 - [휴가] 휴가 발생 조회, 등록 수정
  final/src/main/java/com/insider/login/leave/controller/LeaveController.java
  final/src/main/java/com/insider/login/leave/dto/LeaveAccrualDTO.java
  final/src/main/java/com/insider/login/leave/entity/LeaveAccrual.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 🥝Refactor

#229 fix #38 - [휴가] 휴가 신청 취소 코드 복구
  final/src/main/java/com/insider/login/leave/controller/LeaveController.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 🌀BugFix

#231 feat #39 - [휴가] 휴가 발생 등록 시 휴가 내역 추가
  final/src/main/java/com/insider/login/leave/entity/Leaves.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 💻Feature

#232 DB수정으로 인해 code 수정
  final/src/main/java/com/insider/login/member/controller/MemberController.java
  final/src/main/java/com/insider/login/member/entity/Member.java
  final/src/main/java/com/insider/login/position/controller/PositionController.java
  final/src/main/java/com/insider/login/position/dto/PositionDTOSecond.java
  final/src/main/java/com/insider/login/position/entity/Position.java
  final/src/main/java/com/insider/login/position/repository/PositionRepository.java
  final/src/main/java/com/insider/login/position/service/PositionService.java
Labels: 🌀BugFix

#233 feat #22 - [출퇴근] 멤버별 출퇴근 시간 정정 내역 조회
  final/http/commute/commute.http
  final/src/main/java/com/insider/login/commute/controller/CommuteController.java
  final/src/main/java/com/insider/login/commute/service/CommuteService.java
Labels: 🎈API, 💻Feature, 🔎Test

#235 feat #40 - [휴가] 휴가 발생 등록
  final/src/main/java/com/insider/login/leave/controller/LeaveController.java
  final/src/main/java/com/insider/login/leave/dto/LeaveMemberDTO.java
  final/src/main/java/com/insider/login/leave/entity/LeaveMember.java
  final/src/main/java/com/insider/login/leave/repository/LeaveMemberRepository.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 🎈API, 💻Feature

#237 Fix#7전자결재직급조회관련수정
  final/src/main/java/com/insider/login/approval/dto/MemberDTO.java
  final/src/main/java/com/insider/login/approval/dto/PositionDTO.java
  final/src/main/java/com/insider/login/approval/entity/Member.java
  final/src/main/java/com/insider/login/approval/entity/Position.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalDepartmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalMemberRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalPositionRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Labels: 🥝Refactor

#238 feat #23 - [출퇴근] position db 설정 변동으로 entity와 dto 매핑 변경
  final/src/main/java/com/insider/login/commute/dto/CommuteMemberDTO.java
  final/src/main/java/com/insider/login/commute/entity/CommuteMember.java
Labels: 🎈API, 🌀BugFix

#243 feat#4 - [채팅] 채팅방 삭제
  .idea/dataSources.xml
  final/http/other/chat.http
  final/src/main/java/com/insider/login/webSocket/Cahtting/config/WebSocketBrokerConfig.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/controller/ChatRoomController.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/EntRoomDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/EnteredRoomDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/entity/ChatRoom.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/repository/EnteredRoomRepository.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/service/ChatRoomService.java
Labels: 🎈API, 💻Feature

#244 부서, 직급 CRUD 기능 구현
  final/src/main/java/com/insider/login/auth/filter/HeaderFilter.java
  final/src/main/java/com/insider/login/auth/filter/JwtAuthorizationFilter.java
  final/src/main/java/com/insider/login/common/utils/TokenUtils.java
  final/src/main/java/com/insider/login/department/controller/DepartmentController.java
  final/src/main/java/com/insider/login/department/dto/DepartmentChangeNameDTO.java
  final/src/main/java/com/insider/login/department/repository/DepartmentRepository.java
  final/src/main/java/com/insider/login/department/service/DepartmentService.java
  final/src/main/java/com/insider/login/position/controller/PositionController.java
  final/src/main/java/com/insider/login/position/dto/PositionChangeNameDTO.java
  final/src/main/java/com/insider/login/position/repository/PositionRepository.java
  final/src/main/java/com/insider/login/position/service/PositionService.java
  final/src/main/resources/application.yml
Labels: 🌀BugFix, 💻Feature

#246 feat #41 - [휴가] 조회 시 page 응답명 통일
  final/src/main/java/com/insider/login/leave/controller/LeaveController.java
Labels: 🥝Refactor

#248 구성원 이미지 저장 경로 설정
  .idea/vcs.xml
  final/src/main/java/com/insider/login/member/controller/MemberController.java
Labels: 🌀BugFix, 💻Feature

#250 feat #42 - [휴가] 휴가 컨트롤러 수정
  final/src/main/java/com/insider/login/leave/controller/LeaveController.java
Labels: 🥝Refactor

#252 feat #43 - [휴가] 휴가 신청 처리 시 처리자 사번 추출
  final/src/main/java/com/insider/login/leave/controller/LeaveController.java
Labels: 🥝Refactor

#254 feat #44 - [휴가] 휴가 정보 계산 리팩토링
  final/src/main/java/com/insider/login/calendar/controller/CalendarContorller.java
  final/src/main/java/com/insider/login/leave/controller/LeaveController.java
  final/src/main/java/com/insider/login/leave/dto/LeaveInfoDTO.java
  final/src/main/java/com/insider/login/leave/repository/LeaveRepository.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
  final/src/main/java/com/insider/login/leave/util/LeaveUtil.java
Labels: 🥝Refactor

#256 feat #45 - [휴가] 휴가 정보 계산 시 사번으로 이름 조회해서 추가
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 🥝Refactor

#258 fix #24 - [출퇴근] 출퇴근 정정 내역 조회 시 기존 출퇴근 데이터 가져오기 로직 추가
  final/http/commute/commute.http
  final/src/main/java/com/insider/login/commute/controller/CommuteController.java
  final/src/main/java/com/insider/login/commute/repository/CommuteMemberRepository.java
  final/src/main/java/com/insider/login/commute/repository/CommuteRepository.java
  final/src/main/java/com/insider/login/commute/service/CommuteService.java
  final/src/main/resources/application.yml
  final/src/test/java/com/insider/login/commute/controller/CommuteControllerTests.java
  final/src/test/java/com/insider/login/commute/service/CommuteServiceTests.java
Labels: 🎈API, 🌀BugFix, 🥝Refactor

#265 feat #14 [수요조사] 수요조사 목록 조회 리팩토링
  final/http/survey/survey.http
  final/src/main/java/com/insider/login/survey/controller/SurveyController.java
  final/src/main/java/com/insider/login/survey/dto/SurveyDTO.java
  final/src/main/java/com/insider/login/survey/repository/SurveyAnswerRepository.java
  final/src/main/java/com/insider/login/survey/repository/SurveyResponseRepository.java
  final/src/main/java/com/insider/login/survey/service/SurveyService.java
  final/src/test/java/com/insider/login/survey/service/SurveyServiceTests.java
Labels: 🥝Refactor

#268 feat #2 - [통계] 금일 출근 현황 / 금일 휴가자 현황
  final/http/note/note.http
  final/src/main/java/com/insider/login/auth/filter/JwtAuthorizationFilter.java
  final/src/main/java/com/insider/login/insite/controller/InsiteController.java
  final/src/main/java/com/insider/login/insite/entity/InsiteMember.java
  final/src/main/java/com/insider/login/insite/entity/insiteCommute/InsiteCommute.java
  final/src/main/java/com/insider/login/insite/entity/insiteDepart/InsiteDepartment.java
  final/src/main/java/com/insider/login/insite/entity/insiteLeave/insiteLeave.java
  final/src/main/java/com/insider/login/insite/repository/InsiteRepository.java
  final/src/main/java/com/insider/login/insite/service/InsiteService.java
  final/src/main/resources/application.yml
Labels: 🎈API, 💻Feature

#272 feat #15 - [수요조사] 등록 로직 리팩토링
  final/src/main/java/com/insider/login/survey/controller/SurveyController.java
  final/src/main/java/com/insider/login/survey/dto/SurveyDTO.java
  final/src/main/java/com/insider/login/survey/service/SurveyService.java
  final/src/test/java/com/insider/login/survey/service/SurveyServiceTests.java
Labels: 🥝Refactor

#273 fix #26 - [출퇴근] 출퇴근 내역 조회 /정정 내역 조회 중 JPA 쿼리 오류 이슈
  final/src/main/java/com/insider/login/commute/dto/CorrectionAndCommuteDTO.java
  final/src/main/java/com/insider/login/commute/dto/CorrectionDTO.java
  final/src/main/java/com/insider/login/commute/repository/CommuteRepository.java
  final/src/main/java/com/insider/login/commute/repository/CorrectionAndCommuteRepository.java
  final/src/main/java/com/insider/login/commute/repository/CorrectionRepository.java
  final/src/main/java/com/insider/login/commute/service/CommuteService.java
Labels: 🌀BugFix

#275 feat #16 - [수요조사]조회 로직 및 DTO, Entity 구조 리팩토링
  final/http/survey/survey.http
  final/src/main/java/com/insider/login/survey/controller/SurveyController.java
  final/src/main/java/com/insider/login/survey/dto/SurveyDTO.java
  final/src/main/java/com/insider/login/survey/entity/Survey.java
  final/src/main/java/com/insider/login/survey/service/SurveyService.java
Labels: 🥝Refactor

#278 fix #27 - [출퇴근] 매핑 수정으로 서비스 전반적인 코드 수정
  final/src/main/java/com/insider/login/commute/builder/CommuteBuilder.java
  final/src/main/java/com/insider/login/commute/controller/CommuteController.java
  final/src/main/java/com/insider/login/commute/dto/CommuteDTO.java
  final/src/main/java/com/insider/login/commute/dto/CommuteDepartmentDTO.java
  final/src/main/java/com/insider/login/commute/dto/CommuteMemberDTO.java
  final/src/main/java/com/insider/login/commute/dto/CorrectionDTO.java
  final/src/main/java/com/insider/login/commute/entity/Commute.java
  final/src/main/java/com/insider/login/commute/entity/CommuteDepartment.java
  final/src/main/java/com/insider/login/commute/entity/CommuteMember.java
  final/src/main/java/com/insider/login/commute/entity/Correction.java
  final/src/main/java/com/insider/login/commute/repository/CommuteDepartmentRepository.java
  final/src/main/java/com/insider/login/commute/repository/CommuteMemberRepository.java
  final/src/main/java/com/insider/login/commute/repository/CommuteRepository.java
  final/src/main/java/com/insider/login/commute/repository/CorrectionRepository.java
  final/src/main/java/com/insider/login/commute/service/CommuteService.java
  final/src/main/java/com/insider/login/config/BeanConfig.java
  final/src/main/java/com/insider/login/other/notice/controller/NoticeController.java
  final/src/test/java/com/insider/login/commute/controller/CommuteControllerTests.java
  final/src/test/java/com/insider/login/commute/service/CommuteServiceTests.java
Labels: 🌀BugFix, 💻Feature, 🔎Test, 🥝Refactor

#288 feat #46 - [휴가] 휴가 신청 관련 로직 리팩토링
  final/http/Leave/Leave.http
  final/src/main/java/com/insider/login/leave/controller/LeaveController.java
  final/src/main/java/com/insider/login/leave/repository/LeaveSubmitRepository.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
  final/src/main/java/com/insider/login/survey/controller/SurveyController.java
  final/src/main/java/com/insider/login/survey/service/SurveyService.java
Labels: 🥝Refactor

#290 feat #1 - [메인] 메인 카드 4개 추가
  .idea/vcs.xml
  final/http/chat/chat.http
  final/src/main/java/com/insider/login/insite/controller/InsiteController.java
  final/src/main/java/com/insider/login/insite/dto/InsiteLeaveInfoDTO.java
  final/src/main/java/com/insider/login/insite/entity/insiteApproval/InsiteApproval.java
  final/src/main/java/com/insider/login/insite/entity/insiteApproval/InsiteApprover.java
  final/src/main/java/com/insider/login/insite/entity/insiteLeave/InsiteLeaveSubmit.java
  final/src/main/java/com/insider/login/insite/entity/insiteLeave/InsiteLeaves.java
  final/src/main/java/com/insider/login/insite/repository/InsiteRepository.java
  final/src/main/java/com/insider/login/insite/service/InsiteService.java
Labels: 🎈API, 💻Feature

#294 feat #47 - [휴가] 휴가 취소 신청 로직 리팩토링
  final/src/main/java/com/insider/login/calendar/controller/CalendarContorller.java
  final/src/main/java/com/insider/login/leave/dto/LeaveInfoDTO.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
  final/src/main/java/com/insider/login/leave/util/LeaveUtil.java
  final/src/test/java/com/insider/login/leave/service/LeavesServiceTests.java
Labels: 🥝Refactor

#295 Fix#5전자결재관련yml수정
  final/http/approval/approval.http
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/main/resources/application.yml
Labels: 💻Feature, 🔎Test

#297 fix #48 - [휴가] 휴가 신청 로직 처리
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 🌀BugFix, 🥝Refactor

#299 feat #14 - [캘린더] 전체 부서 일정 조회 로직
  final/src/main/java/com/insider/login/calendar/service/CalendarService.java
Labels: 💻Feature

#300 fix#3 전자결재 반려날짜 및 repository 전면 수정
  final/http/approval/approval.http
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/dto/ApprovalDTO.java
  final/src/main/java/com/insider/login/approval/dto/AttachmentDTO.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
  final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
  final/src/main/java/com/insider/login/approval/repository/AttachmentRepository.java
  final/src/main/java/com/insider/login/approval/repository/ReferencerRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/test/java/com/insider/login/approval/controller/ApprovalControllerTest.java
  final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
  final/src/test/java/com/insider/login/commute/controller/CommuteControllerTests.java
Labels: 🌀BugFix, 💻Feature, 🔎Test, 🥝Refactor

#302 Fix#9 전자결재반려날짜
  final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
  final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Labels: 💻Feature, 🔎Test, 🥝Refactor

#305 feat #4 - [통계] 전체적인 리팩토링
  .idea/dataSources.xml
  .idea/vcs.xml
  final/http/user/user.http
  final/src/main/java/com/insider/login/insite/controller/InsiteController.java
  final/src/main/java/com/insider/login/insite/entity/InsiteMember.java
  final/src/main/java/com/insider/login/insite/repository/InsiteRepository.java
  final/src/main/java/com/insider/login/insite/service/InsiteService.java
  final/src/main/resources/application.yml
Labels: 🎈API, 🌀BugFix, 💻Feature, 🥝Refactor

#308 feat #31 - [휴가] 휴가 처리 시 발생 이벤트
  final/src/main/java/com/insider/login/leave/dto/SubmitAndCalendarDTO.java
  final/src/main/java/com/insider/login/leave/entity/LeaveMember.java
  final/src/main/java/com/insider/login/leave/entity/SubmitAndCalendar.java
  final/src/main/java/com/insider/login/leave/repository/LeaveCalendarRepository.java
  final/src/main/java/com/insider/login/leave/repository/LeaveDepartmentRepository.java
  final/src/main/java/com/insider/login/leave/repository/LeaveMemberRepository.java
  final/src/main/java/com/insider/login/leave/repository/LeavePositionRepository.java
  final/src/main/java/com/insider/login/leave/repository/SubmitAndCalendarRepository.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 💻Feature

#310 feat #28 - [출퇴근] 출퇴근 내역 조회/ 출퇴근 정정 내역 조회 리팩토링
  .idea/dataSources.xml
  final/src/main/java/com/insider/login/commute/controller/CommuteController.java
  final/src/main/java/com/insider/login/commute/dto/CorrectionDTO.java
  final/src/main/java/com/insider/login/commute/service/CommuteService.java
  final/src/test/java/com/insider/login/leave/service/LeavesServiceTests.java
Labels: 🥝Refactor

#312 feat #7 - [채팅] 채팅 메시지 저장 / 기존 메시지 불러오기
  final/http/chat/chat.http
  final/http/user/user.http
  final/src/main/java/com/insider/login/webSocket/Cahtting/controller/MessageController.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/MessageDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/entity/ChatRoom.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/entity/Messages.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/repository/MessageRepository.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/service/ChatRoomService.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/service/MessageService.java
Labels: 🎈API, 🌀BugFix, 💻Feature, 🥝Refactor

#315 fix#9 전자결재 재임시저장 수정
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
Labels: 🥝Refactor

#317 feat #8 - [채팅] 채팅방 삭제 -> delete : put 변경
  final/http/chat/chat.http
  final/src/main/java/com/insider/login/webSocket/Cahtting/controller/ChatRoomController.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/controller/MessageController.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/dto/EntRoomReqDTO.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/entity/ChatRoom.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/repository/EnteredRoomRepository.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/service/ChatRoomService.java
Labels: 🎈API, 🌀BugFix, 🥝Refactor

#319 feat #29 - [출퇴근] 기존 출퇴근 기록이 없을 때 출퇴근 정정 등록 기능 추가
  final/http/commute/commute.http
  final/http/notice/notice.http
  final/src/main/java/com/insider/login/commute/controller/CommuteController.java
  final/src/main/java/com/insider/login/commute/dto/CorrectionAndCommuteDTO.java
  final/src/main/java/com/insider/login/commute/dto/NewCommuteDTO.java
  final/src/main/java/com/insider/login/commute/dto/NewCorrectionDTO.java
  final/src/main/java/com/insider/login/commute/entity/NewCorrection.java
  final/src/main/java/com/insider/login/commute/service/CommuteService.java
  final/src/main/java/com/insider/login/notice/controller/NoticeController.java
  final/src/main/java/com/insider/login/webSocket/Cahtting/config/WebSocketConfig.java
  final/src/test/java/com/insider/login/commute/service/CommuteServiceTests.java
  final/src/test/java/com/insider/login/notice/service/NoticeServiceTests.java
Labels: 🎈API, 💻Feature

#322 feat #30 - [출퇴근] 출퇴근 내역이 없을 때 출퇴근 정정 등록 시, 처리하는 로직
  .idea/dataSources.xml
  final/src/main/java/com/insider/login/commute/controller/CommuteController.java
  final/src/main/java/com/insider/login/commute/service/CommuteService.java
Labels: 🎈API, 💻Feature

#323 Fix#7전자결재 전자결재번호수정
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
Labels: 🌀BugFix, 🥝Refactor

#325 feat #49 - [휴가] 휴가 보유 내역 조회 수정
  final/src/main/java/com/insider/login/leave/repository/LeaveMemberRepository.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 🥝Refactor

#327 feat #5 - [통계] 메인페이지 잔여휴가일수 변경
  .idea/dataSources.xml
  final/src/main/java/com/insider/login/insite/controller/InsiteController.java
  final/src/main/java/com/insider/login/insite/dto/InsiteLeaveInfoDTO.java
  final/src/main/java/com/insider/login/insite/repository/InsiteRepository.java
  final/src/main/java/com/insider/login/insite/service/InsiteService.java
  final/src/main/resources/application.yml
Labels: 🌀BugFix, 🥝Refactor

#331 feat #6 - [통계] 메인페이지 상신인 조건 추가
  final/src/main/java/com/insider/login/insite/controller/InsiteController.java
  final/src/main/java/com/insider/login/insite/repository/InsiteRepository.java
  final/src/main/java/com/insider/login/insite/service/InsiteService.java
Labels: 🌀BugFix, 🥝Refactor

#329 feat#22 전자결재 파일 다운로드
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/resources/testfiles/image03.pdf
  final/src/main/resources/testfiles/image03.png
  final/src/main/resources/testfiles/전자결재서류.txt
Labels: 💻Feature

#332 feat#22 파일 다운로드
  final/http/approval/approval.http
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/repository/ApprovalMemberRepository.java
Labels: 💻Feature

#333 Fix#10 전자결재 임시저장 후 기안 수정
  final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
  final/src/main/java/com/insider/login/approval/service/ApprovalService.java
Labels: 🌀BugFix, 🥝Refactor

#335 feat #50 - [휴가] 휴가 발생 로직 수정
  final/src/main/java/com/insider/login/leave/controller/LeaveController.java
  final/src/main/java/com/insider/login/leave/dto/LeaveAccrualDTO.java
  final/src/main/java/com/insider/login/leave/service/LeaveService.java
Labels: 💻Feature, 🥝Refactor

#337 출퇴근 시간 정정 요청 등록시 출퇴근 내역 미존재건 처리 수정
  final/http/notice/notice.http
  final/src/main/java/com/insider/login/commute/controller/CommuteController.java
  final/src/main/java/com/insider/login/commute/service/CommuteService.java
  final/src/main/java/com/insider/login/notice/controller/NoticeController.java
  final/src/main/resources/application.yml
Labels: 🎈API, 💻Feature
